#!/usr/bin/env python3
"""Turn margaret/img/*.{jpg,png,webp} into photos.js for the served pages.

Slots left empty keep the synthesised plate from data.js. The single-file
artifact build inlines the same images itself; this file is only for the
folder-served version.
"""
import base64, json, pathlib

HERE = pathlib.Path(__file__).parent
SLOTS = {
    'eleanorPortrait': 'eleanor-portrait', 'companionFace': 'companion-face',
    'sarahWedding': 'sarah-wedding', 'sarahTea': 'sarah-tea',
    'garden': 'garden', 'piano': 'piano', 'robert': 'robert', 'boat': 'boat',
    'grandchildren': 'grandchildren', 'kitchen': 'kitchen', 'seaside': 'seaside',
}
EXTS = ('.jpg', '.jpeg', '.png', '.webp')


def find(stem):
    for ext in EXTS:
        p = HERE / 'img' / (stem + ext)
        if p.exists():
            return p
    return None


def photo_map(inline=False):
    out = {}
    for slot, stem in SLOTS.items():
        p = find(stem)
        if not p:
            continue
        if inline:
            mime = 'image/jpeg' if p.suffix in ('.jpg', '.jpeg') else 'image/' + p.suffix[1:]
            out[slot] = 'data:%s;base64,%s' % (mime, base64.b64encode(p.read_bytes()).decode())
        else:
            out[slot] = 'img/' + p.name
    return out


if __name__ == '__main__':
    m = photo_map()
    (HERE / 'photos.js').write_text(
        '/* Generated by build-photos.py — real photographs, one per slot.\n'
        '   Loaded before data.js; anything absent keeps its synthesised plate. */\n'
        'window.MARGARET_PHOTOS = %s;\n' % json.dumps(m, indent=2), encoding='utf8')
    print('photos.js — %d of %d slots have a photograph' % (len(m), len(SLOTS)))
    for slot in SLOTS:
        if slot not in m:
            print('  still a plate:', SLOTS[slot])
