name: Deploy fitness tracker

on:
  push:
    branches: [main]
    paths: ['fitness-tracker/**', '.github/workflows/fitness-tracker.yml']
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches: [main]
    paths: ['fitness-tracker/**']

jobs:
  build_and_deploy:
    if: github.event_name != 'pull_request' || github.event.action != 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: upload
          app_location: 'fitness-tracker'
          api_location: 'fitness-tracker/azure-api'
          output_location: ''

  close_pull_request:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: close
